name: Build actions
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install pnpm -g
      - run: pnpm install
      - name: Build app
        run: pnpm run build
      - run: ls -l
