name: Say Hello
on:
  push:
    branches:
      - master
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo of the message
        run: echo "Hello world"
      - run: date
      - run: ls -l
      - run: pwd
      - run: uname -a
